name: Awesome Bot
on:
  push:
  pull_request:
  schedule:
    - cron: '30 5 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Awesome Bot
      run: gem install awesome_bot

    - name: Run Awesome Bot
      run: awesome_bot README.md --request-delay 1 --set-timeout 5 --white-list awesome.re,redmine.org,support.gurock.com
