name: Awesome Bot
on:
  push:
  pull_request:
  schedule:
    - cron: '30 5 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Markdown lint for README
      uses: docker://avtodev/markdown-lint:v1
      with:
        config: ./.markdownlint.json
        args: ./README.md
